// Generates site/js/data/strings.js and site/js/data/lesson-copy.js from the approved
// copy files, so every UI string is placed verbatim (never retyped by hand).
// Run: node tools/build-strings.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const uiMd = readFileSync(join(root, "final-ui-copy.md"), "utf8");
const lessonsMd = readFileSync(join(root, "final-lessons.md"), "utf8");

const DASHES = /[–—]/;

function cells(line) {
  return line.split("|").slice(1, -1).map((c) => c.trim());
}
function unkey(cell) {
  const m = cell.match(/^`([^`]+)`$/);
  return m ? m[1] : null;
}
function isReference(value) {
  return /^\(?see /i.test(value) || value === "";
}

function parseUi(md) {
  const out = {};
  for (const line of md.split(/\r?\n/)) {
    if (!line.startsWith("| `")) continue;
    const c = cells(line);
    const key = unkey(c[0]);
    if (!key || key.includes("*")) continue;
    if (c.length === 4) {
      // Tool table: Key | Label | aria-label | Tooltip
      const [, label, aria, tip] = c;
      if (label) out[key] = label;
      if (aria && aria !== "(sheet title)") out[key + ".aria"] = aria;
      if (tip) out[key + ".tooltip"] = tip;
      continue;
    }
    const value = c[1];
    if (isReference(value)) continue;
    if (key in out) continue; // the toast index repeats keys already defined
    out[key] = value;
  }
  // Width names are given in a prose line, not a table row.
  const w = md.match(/`tool\.width\.s` (\S+) · `tool\.width\.m` (\S+) · `tool\.width\.l` (\S+)\./);
  if (!w) throw new Error("width names line not found");
  out["tool.width.s"] = w[1];
  out["tool.width.m"] = w[2];
  out["tool.width.l"] = w[3];
  return out;
}

function parseThemes(md) {
  const block = md.match(/export const THEMES = \[([\s\S]*?)\];/);
  if (!block) throw new Error("themes block not found");
  return [...block[1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
}

function parseLessons(md) {
  const out = {};
  for (const line of md.split(/\r?\n/)) {
    if (!line.startsWith("| `")) continue;
    const c = cells(line);
    const key = unkey(c[0]);
    if (!key) continue;
    out[key] = c[1];
  }
  return out;
}

const ui = parseUi(uiMd);
const themes = parseThemes(uiMd);
const lessons = parseLessons(lessonsMd);

for (const [k, v] of Object.entries({ ...ui, ...lessons })) {
  if (DASHES.test(v)) throw new Error(`dash found in ${k}`);
}
if (themes.length !== 52) throw new Error(`expected 52 themes, got ${themes.length}`);
for (const t of themes) if (t.length > 16) throw new Error(`theme too long: ${t}`);

const header = "// GENERATED by tools/build-strings.mjs from the approved copy. Do not edit by hand.\n";
writeFileSync(
  join(root, "site/js/data/strings.js"),
  header + "export const STRINGS = " + JSON.stringify(ui, null, 2) + ";\n"
);
writeFileSync(
  join(root, "site/js/data/themes.js"),
  header + "export const THEMES = " + JSON.stringify(themes, null, 2) + ";\n"
);
writeFileSync(
  join(root, "site/js/data/lesson-copy.js"),
  header + "export const LESSON_COPY = " + JSON.stringify(lessons, null, 2) + ";\n"
);
console.log(`ui keys: ${Object.keys(ui).length}, themes: ${themes.length}, lesson keys: ${Object.keys(lessons).length}`);
